### ISSUE TITLE
Impossible to display translation values

### ISSUE THREAD

**Issue by workaandrey** [Propaganistas/Laravel-Translatable-Bootforms#17]
Imagine if you have edit form for object Shop and you need to support en and fr locales.
You will have input `{!! TranslatableBootForm::text('Title', 'title')->required(true)->value($shop->title) !!}`
In my case i'm getting this https://goo.gl/PrsAZ9 even if for FR locale value is "Foo Bar"

**Comment by Propaganistas** [comment]
Valid point you got there. 

Directly passing `$shop->title` will never work since this implies fetching a translated value only once using the current locale at the time of evaluation. To be able to support this use case, a Closure would be necessary.

I've made some quick (dirty) changes in the `dev-callable-argument` branch. Could you please check that one out and try the code below?

```php
{!! TranslatableBootForm::text('Title', 'title')
                        ->required(true)
                        ->value(function($locale) use ($shop) {
                           return $shop->translate($locale)->title;
                        })
!!}
```

@sdebacker I'd like your opinion on this. Do you think the changes in the mentioned branch are viable? They inevitably imply that callable arguments will never make it to BootForm. But I don't think BootForm has any method that accepts closure arguments?

**Comment by sdebacker** [comment]
Sorry I missed this conversation.
@workaandrey Why do you want to manually set the value in place of bind the model to the form ?
@Propaganistas If we have to manually set the value, why not use the monolingual Bootform facade ?

**Comment by sdebacker** [comment]
```php
{!! BootForm::text('Title (fr)', 'fr[title]')->required(true)->value($shop->translate('fr')->title) !!}
{!! BootForm::text('Title (en)', 'fr[title]')->required(true)->value($shop->translate('en')->title) !!}
```

**Comment by Propaganistas** [comment]
Mentioned branch merged. Please update to v1.4.0
