### ISSUE TITLE
FatalErrorException in FormGroup.php line 0

### ISSUE THREAD

**Issue by sdebacker** [Propaganistas/Laravel-Translatable-Bootforms#4]
I have a category_id select/option element (see code bellow), if I set the validation rule category_id to required in Laravel, I get an Exception when I submit the form. The exception is not present with only Bootforms and Translatable package installed.

```php
{!! BootForm::select('Categories', 'category_id', ['' => 'Choose…', '0' => 'cat 1', '1' => 'cat 1']) !!}
```

**Comment by Propaganistas** [comment]
Please provide more information (e.g. the exception).

**Comment by sdebacker** [comment]
Here it is:

[2016-01-22 08:21:32] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Method AdamWathan\Form\Elements\Text::__toString() must not throw an exception, caught ErrorException: Array to string conversion in /Users/samuel/Sites/aparte-editions.be/vendor/adamwathan/bootforms/src/AdamWathan/BootForms/Elements/FormGroup.php:0
Stack trace:
#0 {main}  

I forget to say that my model here is a simple model that doesn't have Translatable trait. Can you reproduce the problem ?

**Comment by Propaganistas** [comment]
Please go to `AdamWathan\Form\Elements\Text::__toString()`, temporarily instert `dd($value)` before the return statement of the `__toString()` method and take a screenshot (expand first 2 or 3 levels) to report back.

Note that the model *must* use Translatable in order for TranslatableBootForms to work properly, since the package modifies the value fetching logic for bound models (which happens to be your piece of code).

Also it's odd that in the OP you report using `select()` while the exception is thrown in the `Text` class.

**Comment by sdebacker** [comment]
I'm sorry for the inconvenience, it seems that the problem is not caused by select and Laravel-Translatable-Bootforms.
Perhaps it is with Bootforms and ```<input type="file" name="images[]" multiple>``` I will investigate more on this. Thanks for your good work.

**Comment by elbakly** [comment]
I have the same bug did you reach anything in this issue

**Comment by elbakly** [comment]
Found the problem I was using {!! TranslatableBootForm::text("Name:", 'name') !!} with the {{!! Form::open()!!}} while you need to use {!! TranslatableBootForm::open() !!}
