### ISSUE TITLE
Old value are empty when validation error occurs in form

### ISSUE THREAD

**Issue by sdebacker** [Propaganistas/Laravel-Translatable-Bootforms#6]
Since version 1.2, when there is a validation error, old values disappear from all translatable fields.
Il rolled back to previous version and all is ok again.

**Comment by Propaganistas** [comment]
I noticed that myself as well and am investigating this. I already narrowed it down to a change in behavior of the Form package since v0.8, but haven't been been able to trace it back completely or to think of a workaround.
Time is getting scarce at the moment, so all help highly appreciated of course!

**Comment by Propaganistas** [comment]
@sdebacker: The problem originated in `adamwathan/form` but is fixed now.

**Comment by sdebacker** [comment]
Nice, thanks for the good work.
